### ISSUE TITLE
It doesn't work in nx console extension in vscode

### ISSUE THREAD

**Issue by maxisam** [Phillip9587/nx-stylelint#81]
Create plugin Thanks for creating this.

However, it doesn't work with vscode nx extension.

**Comment by Phillip9587** [comment]
@maxisam I just checked nx-stylelint with the nx console extension and it works fine. 

![image](https://user-images.githubusercontent.com/17254592/121305546-fe14f700-c8fd-11eb-9c45-42a2ca96ba76.png)

 Please describe your problem in detail and provide a error log and the output of `nx report` so that i can try to reproduce your problem.

**Comment by maxisam** [comment]
It is kinda crazy. It works now. I had a full reboot and everything works. Thanks!

**Comment by maxisam** [comment]
@Phillip9587 Just another thing. Is it possible to change the default settings and save it somewhere in the config ?

**Comment by Phillip9587** [comment]
@maxisam To change the stylelint configuration edit the `.stylelintrc.json` files: https://stylelint.io/user-guide/configure

**Comment by maxisam** [comment]
Sorry,  I meant --style and --format=json

**Comment by Phillip9587** [comment]
@maxisam Ok i'm sorry. You can configure the nx-stylelint generators just like any other schematic or generator:  https://nx.dev/latest/react/core-concepts/configuration#generators

**Comment by maxisam** [comment]
@Phillip9587  Thanks! that works. In case anyone has the same question

put this in generator

```json
      "nx-stylelint": {
         "configuration": {
            "style": "scss"
         }
      }
```
